server:
  port: 9001
  servlet:
    application-display-name: sso-auth-server
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
mybatis:
  type-aliases-package: com.zhuang.domain
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.zhuang: debug
#自定义属性，配置私钥路径
rsa:
  key:
    privateKeyPath: D:\auth_key\rsa_key