minio:
  # 访问的url
  endpoint: https://101.43.21.132
  # API的端口
  port: 9001
  # 秘钥
  accessKey: U2L0FKK2ZXCBEQF6R1FO
  secretKey: 86+up6VAxQlBZ88waNUYhHVbc1r8S5YAZyBKMoRH
  secure: false
  bucket-name: test # 桶名 我这是给出了一个默认桶名
  image-size: 10485760 # 我在这里设定了 图片文件的最大大小
  file-size: 1073741824 # 此处是设定了文件的最大大小

server:
  port: 8088